"""Tests for pedagogy-library/_schema/validate.py.

Each test exercises one failure mode the validator must catch. The exemplar
chapter (testing-effect.md) is the gold standard; fixtures are generated by
copying the exemplar and breaking exactly one thing.

Run from this directory:

    python -m pytest test_validate.py -v
"""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest

from validate import validate_chapter

HERE = Path(__file__).resolve().parent
LIBRARY_ROOT = HERE.parent
EXEMPLAR = LIBRARY_ROOT / "01-learning-science" / "testing-effect.md"
FIXTURES_DIR = HERE / "test_fixtures"


# ---------------------------------------------------------------------------
# Fixture generation
# ---------------------------------------------------------------------------

def _read_exemplar() -> str:
    return EXEMPLAR.read_text(encoding="utf-8")


def _write_fixture(name: str, content: str) -> Path:
    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
    path = FIXTURES_DIR / name
    path.write_text(content, encoding="utf-8")
    return path


def _strip_frontmatter_field(content: str, field: str) -> str:
    """Remove a single top-level field from the YAML frontmatter block.

    Handles both scalar (``id: foo``) and block (``key_sources:\\n  - ...``)
    forms by deleting the field's header line plus any subsequent indented
    continuation lines until the next top-level key or the closing ``---``.
    """
    lines = content.splitlines(keepends=True)
    if not lines or lines[0].rstrip("\r\n") != "---":
        raise AssertionError("Exemplar missing opening frontmatter delimiter.")

    out: list[str] = [lines[0]]
    i = 1
    in_field = False
    while i < len(lines):
        line = lines[i]
        stripped = line.rstrip("\r\n")
        if stripped == "---":
            out.extend(lines[i:])
            return "".join(out)
        if in_field:
            # Continuation lines are indented or blank; non-indented non-blank
            # marks the start of the next top-level key.
            if line.startswith((" ", "\t")) or stripped == "":
                i += 1
                continue
            in_field = False
            # fall through to evaluate this line as a new key
        if stripped.startswith(f"{field}:"):
            in_field = True
            i += 1
            continue
        out.append(line)
        i += 1
    raise AssertionError("Exemplar missing closing frontmatter delimiter.")


# ---------------------------------------------------------------------------
# pytest fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module", autouse=True)
def _ensure_clean_fixtures_dir():
    if FIXTURES_DIR.exists():
        shutil.rmtree(FIXTURES_DIR)
    FIXTURES_DIR.mkdir(parents=True)
    yield
    # Leave fixtures on disk after tests for debugging; remove if you'd rather
    # not see them.


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

def test_validator_accepts_valid_chapter():
    """The exemplar is the gold standard; validator must accept it."""
    result = validate_chapter(EXEMPLAR)
    assert result.ok, (
        "Validator rejected the exemplar; the validator (or schema) is "
        "wrong, not the exemplar. Errors:\n  - "
        + "\n  - ".join(result.errors)
    )
    assert result.errors == []


def test_validator_rejects_missing_required_field():
    """Dropping the ``id`` frontmatter field must produce an error."""
    content = _strip_frontmatter_field(_read_exemplar(), "id")
    fixture = _write_fixture("missing_id.md", content)

    result = validate_chapter(fixture)
    assert not result.ok
    assert any("id" in e for e in result.errors), (
        f"Expected an error mentioning 'id'; got: {result.errors!r}"
    )


def test_validator_rejects_too_few_citations():
    """``key_sources`` with fewer than 5 entries must fail."""
    original = _read_exemplar()
    # Remove the last 4 source lines so only 3 remain (exemplar has 7).
    lines = original.splitlines(keepends=True)
    src_indices = [
        i for i, line in enumerate(lines) if line.lstrip().startswith("- \"")
        and 'doi' in line.lower()
    ]
    assert len(src_indices) >= 5, "Could not locate citation lines in exemplar."
    to_drop = set(src_indices[3:])  # keep first 3, drop the rest
    new_lines = [line for i, line in enumerate(lines) if i not in to_drop]
    fixture = _write_fixture("too_few_citations.md", "".join(new_lines))

    result = validate_chapter(fixture)
    assert not result.ok
    assert any("key_sources" in e for e in result.errors), (
        f"Expected an error mentioning 'key_sources'; got: {result.errors!r}"
    )


def test_validator_rejects_missing_section():
    """Removing ``## Quality signal`` must fail the section-order check."""
    original = _read_exemplar()
    lines = original.splitlines(keepends=True)
    # Find the Quality signal heading and drop through to the next H2.
    start = next(
        i for i, line in enumerate(lines)
        if line.rstrip().startswith("## Quality signal")
    )
    end = next(
        i for i in range(start + 1, len(lines))
        if lines[i].rstrip().startswith("## ")
    )
    new_lines = lines[:start] + lines[end:]
    fixture = _write_fixture("missing_quality_signal.md", "".join(new_lines))

    result = validate_chapter(fixture)
    assert not result.ok
    assert any("Quality signal" in e for e in result.errors), (
        f"Expected an error mentioning the missing 'Quality signal' section; "
        f"got: {result.errors!r}"
    )


def test_validator_rejects_too_short_file():
    """A chapter under 120 lines must fail the length check."""
    original = _read_exemplar()
    lines = original.splitlines(keepends=True)
    # Find the closing frontmatter delimiter; preserve frontmatter intact.
    delim_indices = [i for i, line in enumerate(lines) if line.rstrip() == "---"]
    assert len(delim_indices) >= 2, "Exemplar frontmatter delimiters not found."
    fm_end = delim_indices[1]

    head = lines[: fm_end + 1]
    # Add a tiny body to keep the file parseable but well under 120 lines.
    tail = [
        "\n",
        "# Stub\n",
        "\n",
        "## One-line claim\n",
        "Stub.\n",
        "\n",
        "## Evidence base\n",
        "Stub.\n",
        "\n",
        "## When to apply\n",
        "Stub.\n",
        "\n",
        "## When NOT to apply\n",
        "Stub.\n",
        "\n",
        "## How to apply\n",
        "Stub.\n",
        "\n",
        "## Common misapplications\n",
        "Stub.\n",
        "\n",
        "## Examples across domains\n",
        "Stub.\n",
        "\n",
        "## Quality signal\n",
        "Stub.\n",
        "\n",
        "## Cross-references\n",
        "Stub.\n",
    ]
    fixture = _write_fixture("too_short.md", "".join(head + tail))
    # Sanity check: the fixture really is short.
    assert len(fixture.read_text(encoding="utf-8").splitlines()) < 120

    result = validate_chapter(fixture)
    assert not result.ok
    assert any(
        "length" in e.lower() or "120" in e or "lines" in e.lower()
        for e in result.errors
    ), f"Expected an error mentioning length/lines; got: {result.errors!r}"


def test_validator_rejects_too_long_file():
    """A chapter over 200 lines must fail the length check."""
    original = _read_exemplar()
    lines = original.splitlines(keepends=True)
    # Append filler paragraphs after the existing body to push past 200 lines.
    filler = ["\nAdditional filler paragraph for length test.\n"] * 50
    fixture = _write_fixture("too_long.md", "".join(lines + filler))
    assert len(fixture.read_text(encoding="utf-8").splitlines()) > 200

    result = validate_chapter(fixture)
    assert not result.ok
    assert any(
        "length" in e.lower() or "200" in e or "lines" in e.lower()
        for e in result.errors
    ), f"Expected an error mentioning length/lines; got: {result.errors!r}"


def test_validator_rejects_bad_id_pattern():
    """``id`` containing uppercase or invalid characters must fail."""
    original = _read_exemplar()
    bad = original.replace("id: testing-effect", "id: Testing_Effect", 1)
    fixture = _write_fixture("bad_id.md", bad)

    result = validate_chapter(fixture)
    assert not result.ok
    assert any("id" in e for e in result.errors)
